name: Ubuntu 20.04

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_gcc_cmake:
    name: gcc and cmake
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install software-properties-common
        run:  sudo apt-get install software-properties-common
      - name: Install gcc compiler, cmake and ninja
        run:  sudo apt-get -y install gcc-10 g++-10 libtbb-dev ccache libtool pkg-config cmake ninja-build
      - name: Install memory watcher dependencies
        run:  "sudo apt-get update && sudo apt-get install -y
               qt5-default qttools5-dev-tools
               qttools5-dev libqt5sql5-sqlite libqt5charts5-dev
               "
      - name: Configure build project
        run: cmake -B build -DCMAKE_UNITY_BUILD=ON -Wno-dev -G "Ninja"
        env:
          CXX: g++-10
          CC: gcc-10
      - name: Build project
        run: cmake --build build
      - name: Run tests
        run: ctest -j 2 --output-on-failure
        working-directory: build
